name: Nueva tarea o comando
description: Prop贸n la creaci贸n de una nueva tarea, sistema o comando para el bot
title: "[][Comando/Tarea] Breve descripci贸n de tu aporte"
labels: ["propuesta", "pendiente revisi贸n"]
body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por contribuir al bot de Latinoland!  
        Por favor, completa los campos a continuaci贸n para que tu propuesta sea revisada m谩s f谩cilmente.

  - type: textarea
    id: nombre
    attributes:
      label: Nombre del comando o tarea
      description: Escribe el nombre del comando o tarea que est谩s proponiendo.
      placeholder: Ejemplo: /ranking, Sistema de puntos, etc.
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label: Descripci贸n
      description: Explica en detalle qu茅 hace este comando o tarea y c贸mo mejorar谩 el bot.
      placeholder: Este comando muestra el ranking de los usuarios m谩s activos del servidor...
    validations:
      required: true

  - type: textarea
    id: ejemplo
    attributes:
      label: Ejemplo de uso
      description: Proporciona un ejemplo claro de c贸mo se utilizar铆a este comando o sistema.
      placeholder: /ranking -> Retorna: 1. Usuario1, 2. Usuario2...
    validations:
      required: true

  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      description: Selecciona el nivel de prioridad para esta propuesta.
      options:
        - Baja
        - Media
        - Alta
      default: Baja
    validations:
      required: true

  - type: checkboxes
    id: consideraciones
    attributes:
      label: Consideraciones adicionales
      description: Marca las opciones relevantes seg煤n tu propuesta.
      options:
        - label: Este comando requiere permisos espec铆ficos (indicar en detalles adicionales)
          required: false
        - label: Esta propuesta necesita recursos externos (APIs, base de datos, etc.)
          required: false

  - type: textarea
    id: detalles
    attributes:
      label: Detalles adicionales
      description: Incluye informaci贸n t茅cnica, requisitos especiales o cualquier otro detalle importante.
      placeholder: Este comando requiere conexi贸n a una base de datos para almacenar los datos de ranking.
      render: text

  - type: checkboxes
    id: terms
    attributes:
      label: T茅rminos de colaboraci贸n
      description: Al enviar este issue, aceptas cumplir con las reglas del proyecto.
      options:
        - label: Acepto seguir las reglas del proyecto
          required: true
